# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhobosObjcExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhobosObjcExample
  pod 'PhobosObjc/Core', :path => '../', :inhibit_warnings => false
  pod 'PhobosObjc/UIComponent', :path => '../', :inhibit_warnings => false
  pod 'PhobosObjcCore', :path => '../', :inhibit_warnings => false, :testspecs => ['Tests']
  pod 'PhobosObjcUIComponent', :path => '../', :inhibit_warnings => false, :testspecs => ['Tests']
end
