os: osx
osx_image: xcode11
language: objective-c
cache:
  bundler: true
  cocoapods: true
  directories:
    # Built-in support for ccache doesn't seem to pick this up
    - $HOME/.ccache

stages:
  - test_core

jobs:
  include:
    # The order of builds matters (even though they are run in parallel):
    # Travis will schedule them in the same order they are listed here.

    - stage: test_core
      env:
        - PROJECT=Core METHOD=pod-lib-lint
      script:
        - bundle install
        - bundle exec fastlane ios lint --env Core
      #before_script:
        #- gem install bundler
        #- bundle install
        #- bundle update fastlane
        
branches:
  only:
    - develop
